name: "pull-request"

on:
  pull_request:

jobs:
  test-develop:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        shell: [angular, dotnet, gleam, haskell, java, node, python, rust]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix develop .#${{ matrix.shell }}

  test-profile:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        package: [dev, dotnet-run, format, github-release, npm-run, tmux]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix profile install .#${{ matrix.package }}
      - run: which ${{ matrix.package }}

  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    needs: [test-develop, test-profile]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - run: gh pr merge --rebase --auto
    env:
      GH_TOKEN: ${{ secrets.GH_REPO_PAT }}
